// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: weather.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WeatherRequest represents the request parameters for weather queries
type WeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat     float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon     float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Exclude []string `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Units   string   `protobuf:"bytes,4,opt,name=units,proto3" json:"units,omitempty"`
	Lang    string   `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *WeatherRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *WeatherRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *WeatherRequest) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *WeatherRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// WeatherCityRequest represents the request parameters for current weather by city
type WeatherCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City  string `protobuf:"bytes,1,opt,name=city,json=q,proto3" json:"city,omitempty"`
	Units string `protobuf:"bytes,2,opt,name=units,proto3" json:"units,omitempty"`
	Lang  string `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
}

func (x *WeatherCityRequest) Reset() {
	*x = WeatherCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherCityRequest) ProtoMessage() {}

func (x *WeatherCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherCityRequest.ProtoReflect.Descriptor instead.
func (*WeatherCityRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherCityRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WeatherCityRequest) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *WeatherCityRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// WeatherCityResponse represents the current weather response by city
type WeatherCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coord      *Coord              `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
	Weather    []*WeatherCondition `protobuf:"bytes,2,rep,name=weather,proto3" json:"weather,omitempty"`
	Base       string              `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Main       *MainWeather        `protobuf:"bytes,4,opt,name=main,proto3" json:"main,omitempty"`
	Visibility int32               `protobuf:"varint,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Wind       *Wind               `protobuf:"bytes,6,opt,name=wind,proto3" json:"wind,omitempty"`
	Rain       *Rain               `protobuf:"bytes,7,opt,name=rain,proto3" json:"rain,omitempty"`
	Clouds     *Clouds             `protobuf:"bytes,8,opt,name=clouds,proto3" json:"clouds,omitempty"`
	Dt         int64               `protobuf:"varint,9,opt,name=dt,proto3" json:"dt,omitempty"`
	Sys        *Sys                `protobuf:"bytes,10,opt,name=sys,proto3" json:"sys,omitempty"`
	Timezone   int32               `protobuf:"varint,11,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Id         int64               `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`
	Name       string              `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	Cod        int32               `protobuf:"varint,14,opt,name=cod,proto3" json:"cod,omitempty"`
}

func (x *WeatherCityResponse) Reset() {
	*x = WeatherCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherCityResponse) ProtoMessage() {}

func (x *WeatherCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherCityResponse.ProtoReflect.Descriptor instead.
func (*WeatherCityResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{2}
}

func (x *WeatherCityResponse) GetCoord() *Coord {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *WeatherCityResponse) GetWeather() []*WeatherCondition {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *WeatherCityResponse) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *WeatherCityResponse) GetMain() *MainWeather {
	if x != nil {
		return x.Main
	}
	return nil
}

func (x *WeatherCityResponse) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *WeatherCityResponse) GetWind() *Wind {
	if x != nil {
		return x.Wind
	}
	return nil
}

func (x *WeatherCityResponse) GetRain() *Rain {
	if x != nil {
		return x.Rain
	}
	return nil
}

func (x *WeatherCityResponse) GetClouds() *Clouds {
	if x != nil {
		return x.Clouds
	}
	return nil
}

func (x *WeatherCityResponse) GetDt() int64 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *WeatherCityResponse) GetSys() *Sys {
	if x != nil {
		return x.Sys
	}
	return nil
}

func (x *WeatherCityResponse) GetTimezone() int32 {
	if x != nil {
		return x.Timezone
	}
	return 0
}

func (x *WeatherCityResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WeatherCityResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WeatherCityResponse) GetCod() int32 {
	if x != nil {
		return x.Cod
	}
	return 0
}

// Coord represents geographical coordinates
type Coord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lon float64 `protobuf:"fixed64,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat float64 `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *Coord) Reset() {
	*x = Coord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coord) ProtoMessage() {}

func (x *Coord) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coord.ProtoReflect.Descriptor instead.
func (*Coord) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{3}
}

func (x *Coord) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Coord) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

// MainWeather represents main weather parameters
type MainWeather struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temp      float64 `protobuf:"fixed64,1,opt,name=temp,proto3" json:"temp,omitempty"`
	FeelsLike float64 `protobuf:"fixed64,2,opt,name=feels_like,json=feelsLike,proto3" json:"feels_like,omitempty"`
	TempMin   float64 `protobuf:"fixed64,3,opt,name=temp_min,json=tempMin,proto3" json:"temp_min,omitempty"`
	TempMax   float64 `protobuf:"fixed64,4,opt,name=temp_max,json=tempMax,proto3" json:"temp_max,omitempty"`
	Pressure  int32   `protobuf:"varint,5,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Humidity  int32   `protobuf:"varint,6,opt,name=humidity,proto3" json:"humidity,omitempty"`
	SeaLevel  int32   `protobuf:"varint,7,opt,name=sea_level,json=seaLevel,proto3" json:"sea_level,omitempty"`
	GrndLevel int32   `protobuf:"varint,8,opt,name=grnd_level,json=grndLevel,proto3" json:"grnd_level,omitempty"`
}

func (x *MainWeather) Reset() {
	*x = MainWeather{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MainWeather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainWeather) ProtoMessage() {}

func (x *MainWeather) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainWeather.ProtoReflect.Descriptor instead.
func (*MainWeather) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{4}
}

func (x *MainWeather) GetTemp() float64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *MainWeather) GetFeelsLike() float64 {
	if x != nil {
		return x.FeelsLike
	}
	return 0
}

func (x *MainWeather) GetTempMin() float64 {
	if x != nil {
		return x.TempMin
	}
	return 0
}

func (x *MainWeather) GetTempMax() float64 {
	if x != nil {
		return x.TempMax
	}
	return 0
}

func (x *MainWeather) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *MainWeather) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *MainWeather) GetSeaLevel() int32 {
	if x != nil {
		return x.SeaLevel
	}
	return 0
}

func (x *MainWeather) GetGrndLevel() int32 {
	if x != nil {
		return x.GrndLevel
	}
	return 0
}

// Wind represents wind information
type Wind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed float64 `protobuf:"fixed64,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Deg   int32   `protobuf:"varint,2,opt,name=deg,proto3" json:"deg,omitempty"`
	Gust  float64 `protobuf:"fixed64,3,opt,name=gust,proto3" json:"gust,omitempty"`
}

func (x *Wind) Reset() {
	*x = Wind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wind) ProtoMessage() {}

func (x *Wind) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wind.ProtoReflect.Descriptor instead.
func (*Wind) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{5}
}

func (x *Wind) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Wind) GetDeg() int32 {
	if x != nil {
		return x.Deg
	}
	return 0
}

func (x *Wind) GetGust() float64 {
	if x != nil {
		return x.Gust
	}
	return 0
}

// Rain represents rain volume
type Rain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OneH   float64 `protobuf:"fixed64,1,opt,name=one_h,json=1h,proto3" json:"one_h,omitempty"`     // Rain volume for last 1 hour
	ThreeH float64 `protobuf:"fixed64,2,opt,name=three_h,json=3h,proto3" json:"three_h,omitempty"` // Rain volume for last 3 hours
}

func (x *Rain) Reset() {
	*x = Rain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rain) ProtoMessage() {}

func (x *Rain) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rain.ProtoReflect.Descriptor instead.
func (*Rain) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{6}
}

func (x *Rain) GetOneH() float64 {
	if x != nil {
		return x.OneH
	}
	return 0
}

func (x *Rain) GetThreeH() float64 {
	if x != nil {
		return x.ThreeH
	}
	return 0
}

// Clouds represents cloudiness
type Clouds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All int32 `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"` // Cloudiness percentage
}

func (x *Clouds) Reset() {
	*x = Clouds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clouds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clouds) ProtoMessage() {}

func (x *Clouds) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clouds.ProtoReflect.Descriptor instead.
func (*Clouds) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{7}
}

func (x *Clouds) GetAll() int32 {
	if x != nil {
		return x.All
	}
	return 0
}

// Sys represents system data
type Sys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Id      int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Sunrise int64  `protobuf:"varint,4,opt,name=sunrise,proto3" json:"sunrise,omitempty"`
	Sunset  int64  `protobuf:"varint,5,opt,name=sunset,proto3" json:"sunset,omitempty"`
}

func (x *Sys) Reset() {
	*x = Sys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sys) ProtoMessage() {}

func (x *Sys) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sys.ProtoReflect.Descriptor instead.
func (*Sys) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{8}
}

func (x *Sys) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Sys) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sys) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Sys) GetSunrise() int64 {
	if x != nil {
		return x.Sunrise
	}
	return 0
}

func (x *Sys) GetSunset() int64 {
	if x != nil {
		return x.Sunset
	}
	return 0
}

type WeatherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat            float64     `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon            float64     `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Timezone       string      `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	TimezoneOffset int32       `protobuf:"varint,4,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`
	Current        *Current    `protobuf:"bytes,5,opt,name=current,proto3" json:"current,omitempty"`
	Minutely       []*Minutely `protobuf:"bytes,6,rep,name=minutely,proto3" json:"minutely,omitempty"`
	Hourly         []*Hourly   `protobuf:"bytes,7,rep,name=hourly,proto3" json:"hourly,omitempty"`
	Daily          []*Daily    `protobuf:"bytes,8,rep,name=daily,proto3" json:"daily,omitempty"`
	Alerts         []*Alert    `protobuf:"bytes,9,rep,name=alerts,proto3" json:"alerts,omitempty"`
}

func (x *WeatherResponse) Reset() {
	*x = WeatherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherResponse) ProtoMessage() {}

func (x *WeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherResponse.ProtoReflect.Descriptor instead.
func (*WeatherResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{9}
}

func (x *WeatherResponse) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *WeatherResponse) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *WeatherResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *WeatherResponse) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *WeatherResponse) GetCurrent() *Current {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *WeatherResponse) GetMinutely() []*Minutely {
	if x != nil {
		return x.Minutely
	}
	return nil
}

func (x *WeatherResponse) GetHourly() []*Hourly {
	if x != nil {
		return x.Hourly
	}
	return nil
}

func (x *WeatherResponse) GetDaily() []*Daily {
	if x != nil {
		return x.Daily
	}
	return nil
}

func (x *WeatherResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type Current struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dt         int64               `protobuf:"varint,1,opt,name=dt,proto3" json:"dt,omitempty"`
	Sunrise    int64               `protobuf:"varint,2,opt,name=sunrise,proto3" json:"sunrise,omitempty"`
	Sunset     int64               `protobuf:"varint,3,opt,name=sunset,proto3" json:"sunset,omitempty"`
	Temp       float64             `protobuf:"fixed64,4,opt,name=temp,proto3" json:"temp,omitempty"`
	FeelsLike  float64             `protobuf:"fixed64,5,opt,name=feels_like,json=feelsLike,proto3" json:"feels_like,omitempty"`
	Pressure   int32               `protobuf:"varint,6,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Humidity   int32               `protobuf:"varint,7,opt,name=humidity,proto3" json:"humidity,omitempty"`
	DewPoint   float64             `protobuf:"fixed64,8,opt,name=dew_point,json=dewPoint,proto3" json:"dew_point,omitempty"`
	Uvi        float64             `protobuf:"fixed64,9,opt,name=uvi,proto3" json:"uvi,omitempty"`
	Clouds     int32               `protobuf:"varint,10,opt,name=clouds,proto3" json:"clouds,omitempty"`
	Visibility int32               `protobuf:"varint,11,opt,name=visibility,proto3" json:"visibility,omitempty"`
	WindSpeed  float64             `protobuf:"fixed64,12,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	WindDeg    int32               `protobuf:"varint,13,opt,name=wind_deg,json=windDeg,proto3" json:"wind_deg,omitempty"`
	WindGust   float64             `protobuf:"fixed64,14,opt,name=wind_gust,json=windGust,proto3" json:"wind_gust,omitempty"`
	Weather    []*WeatherCondition `protobuf:"bytes,15,rep,name=weather,proto3" json:"weather,omitempty"`
}

func (x *Current) Reset() {
	*x = Current{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Current) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Current) ProtoMessage() {}

func (x *Current) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Current.ProtoReflect.Descriptor instead.
func (*Current) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{10}
}

func (x *Current) GetDt() int64 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Current) GetSunrise() int64 {
	if x != nil {
		return x.Sunrise
	}
	return 0
}

func (x *Current) GetSunset() int64 {
	if x != nil {
		return x.Sunset
	}
	return 0
}

func (x *Current) GetTemp() float64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *Current) GetFeelsLike() float64 {
	if x != nil {
		return x.FeelsLike
	}
	return 0
}

func (x *Current) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Current) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Current) GetDewPoint() float64 {
	if x != nil {
		return x.DewPoint
	}
	return 0
}

func (x *Current) GetUvi() float64 {
	if x != nil {
		return x.Uvi
	}
	return 0
}

func (x *Current) GetClouds() int32 {
	if x != nil {
		return x.Clouds
	}
	return 0
}

func (x *Current) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *Current) GetWindSpeed() float64 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *Current) GetWindDeg() int32 {
	if x != nil {
		return x.WindDeg
	}
	return 0
}

func (x *Current) GetWindGust() float64 {
	if x != nil {
		return x.WindGust
	}
	return 0
}

func (x *Current) GetWeather() []*WeatherCondition {
	if x != nil {
		return x.Weather
	}
	return nil
}

type Minutely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dt            int64   `protobuf:"varint,1,opt,name=dt,proto3" json:"dt,omitempty"`
	Precipitation float64 `protobuf:"fixed64,2,opt,name=precipitation,proto3" json:"precipitation,omitempty"`
}

func (x *Minutely) Reset() {
	*x = Minutely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Minutely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Minutely) ProtoMessage() {}

func (x *Minutely) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Minutely.ProtoReflect.Descriptor instead.
func (*Minutely) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{11}
}

func (x *Minutely) GetDt() int64 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Minutely) GetPrecipitation() float64 {
	if x != nil {
		return x.Precipitation
	}
	return 0
}

type Hourly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dt         int64               `protobuf:"varint,1,opt,name=dt,proto3" json:"dt,omitempty"`
	Temp       float64             `protobuf:"fixed64,2,opt,name=temp,proto3" json:"temp,omitempty"`
	FeelsLike  float64             `protobuf:"fixed64,3,opt,name=feels_like,json=feelsLike,proto3" json:"feels_like,omitempty"`
	Pressure   int32               `protobuf:"varint,4,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Humidity   int32               `protobuf:"varint,5,opt,name=humidity,proto3" json:"humidity,omitempty"`
	DewPoint   float64             `protobuf:"fixed64,6,opt,name=dew_point,json=dewPoint,proto3" json:"dew_point,omitempty"`
	Uvi        float64             `protobuf:"fixed64,7,opt,name=uvi,proto3" json:"uvi,omitempty"`
	Clouds     int32               `protobuf:"varint,8,opt,name=clouds,proto3" json:"clouds,omitempty"`
	Visibility int32               `protobuf:"varint,9,opt,name=visibility,proto3" json:"visibility,omitempty"`
	WindSpeed  float64             `protobuf:"fixed64,10,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	WindDeg    int32               `protobuf:"varint,11,opt,name=wind_deg,json=windDeg,proto3" json:"wind_deg,omitempty"`
	WindGust   float64             `protobuf:"fixed64,12,opt,name=wind_gust,json=windGust,proto3" json:"wind_gust,omitempty"`
	Weather    []*WeatherCondition `protobuf:"bytes,13,rep,name=weather,proto3" json:"weather,omitempty"`
	Pop        float64             `protobuf:"fixed64,14,opt,name=pop,proto3" json:"pop,omitempty"` // Probability of precipitation
}

func (x *Hourly) Reset() {
	*x = Hourly{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hourly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hourly) ProtoMessage() {}

func (x *Hourly) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hourly.ProtoReflect.Descriptor instead.
func (*Hourly) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{12}
}

func (x *Hourly) GetDt() int64 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Hourly) GetTemp() float64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *Hourly) GetFeelsLike() float64 {
	if x != nil {
		return x.FeelsLike
	}
	return 0
}

func (x *Hourly) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Hourly) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Hourly) GetDewPoint() float64 {
	if x != nil {
		return x.DewPoint
	}
	return 0
}

func (x *Hourly) GetUvi() float64 {
	if x != nil {
		return x.Uvi
	}
	return 0
}

func (x *Hourly) GetClouds() int32 {
	if x != nil {
		return x.Clouds
	}
	return 0
}

func (x *Hourly) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *Hourly) GetWindSpeed() float64 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *Hourly) GetWindDeg() int32 {
	if x != nil {
		return x.WindDeg
	}
	return 0
}

func (x *Hourly) GetWindGust() float64 {
	if x != nil {
		return x.WindGust
	}
	return 0
}

func (x *Hourly) GetWeather() []*WeatherCondition {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *Hourly) GetPop() float64 {
	if x != nil {
		return x.Pop
	}
	return 0
}

type Daily struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dt        int64               `protobuf:"varint,1,opt,name=dt,proto3" json:"dt,omitempty"`
	Sunrise   int64               `protobuf:"varint,2,opt,name=sunrise,proto3" json:"sunrise,omitempty"`
	Sunset    int64               `protobuf:"varint,3,opt,name=sunset,proto3" json:"sunset,omitempty"`
	Moonrise  int64               `protobuf:"varint,4,opt,name=moonrise,proto3" json:"moonrise,omitempty"`
	Moonset   int64               `protobuf:"varint,5,opt,name=moonset,proto3" json:"moonset,omitempty"`
	MoonPhase float64             `protobuf:"fixed64,6,opt,name=moon_phase,json=moonPhase,proto3" json:"moon_phase,omitempty"`
	Summary   string              `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Temp      *Temperature        `protobuf:"bytes,8,opt,name=temp,proto3" json:"temp,omitempty"`
	FeelsLike *FeelsLike          `protobuf:"bytes,9,opt,name=feels_like,json=feelsLike,proto3" json:"feels_like,omitempty"`
	Pressure  int32               `protobuf:"varint,10,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Humidity  int32               `protobuf:"varint,11,opt,name=humidity,proto3" json:"humidity,omitempty"`
	DewPoint  float64             `protobuf:"fixed64,12,opt,name=dew_point,json=dewPoint,proto3" json:"dew_point,omitempty"`
	WindSpeed float64             `protobuf:"fixed64,13,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	WindDeg   int32               `protobuf:"varint,14,opt,name=wind_deg,json=windDeg,proto3" json:"wind_deg,omitempty"`
	WindGust  float64             `protobuf:"fixed64,15,opt,name=wind_gust,json=windGust,proto3" json:"wind_gust,omitempty"`
	Weather   []*WeatherCondition `protobuf:"bytes,16,rep,name=weather,proto3" json:"weather,omitempty"`
	Clouds    int32               `protobuf:"varint,17,opt,name=clouds,proto3" json:"clouds,omitempty"`
	Pop       float64             `protobuf:"fixed64,18,opt,name=pop,proto3" json:"pop,omitempty"` // Probability of precipitation
	Rain      float64             `protobuf:"fixed64,19,opt,name=rain,proto3" json:"rain,omitempty"`
	Uvi       float64             `protobuf:"fixed64,20,opt,name=uvi,proto3" json:"uvi,omitempty"`
}

func (x *Daily) Reset() {
	*x = Daily{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Daily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Daily) ProtoMessage() {}

func (x *Daily) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Daily.ProtoReflect.Descriptor instead.
func (*Daily) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{13}
}

func (x *Daily) GetDt() int64 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Daily) GetSunrise() int64 {
	if x != nil {
		return x.Sunrise
	}
	return 0
}

func (x *Daily) GetSunset() int64 {
	if x != nil {
		return x.Sunset
	}
	return 0
}

func (x *Daily) GetMoonrise() int64 {
	if x != nil {
		return x.Moonrise
	}
	return 0
}

func (x *Daily) GetMoonset() int64 {
	if x != nil {
		return x.Moonset
	}
	return 0
}

func (x *Daily) GetMoonPhase() float64 {
	if x != nil {
		return x.MoonPhase
	}
	return 0
}

func (x *Daily) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Daily) GetTemp() *Temperature {
	if x != nil {
		return x.Temp
	}
	return nil
}

func (x *Daily) GetFeelsLike() *FeelsLike {
	if x != nil {
		return x.FeelsLike
	}
	return nil
}

func (x *Daily) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Daily) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Daily) GetDewPoint() float64 {
	if x != nil {
		return x.DewPoint
	}
	return 0
}

func (x *Daily) GetWindSpeed() float64 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *Daily) GetWindDeg() int32 {
	if x != nil {
		return x.WindDeg
	}
	return 0
}

func (x *Daily) GetWindGust() float64 {
	if x != nil {
		return x.WindGust
	}
	return 0
}

func (x *Daily) GetWeather() []*WeatherCondition {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *Daily) GetClouds() int32 {
	if x != nil {
		return x.Clouds
	}
	return 0
}

func (x *Daily) GetPop() float64 {
	if x != nil {
		return x.Pop
	}
	return 0
}

func (x *Daily) GetRain() float64 {
	if x != nil {
		return x.Rain
	}
	return 0
}

func (x *Daily) GetUvi() float64 {
	if x != nil {
		return x.Uvi
	}
	return 0
}

type Temperature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day   float64 `protobuf:"fixed64,1,opt,name=day,proto3" json:"day,omitempty"`
	Min   float64 `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max   float64 `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	Night float64 `protobuf:"fixed64,4,opt,name=night,proto3" json:"night,omitempty"`
	Eve   float64 `protobuf:"fixed64,5,opt,name=eve,proto3" json:"eve,omitempty"`
	Morn  float64 `protobuf:"fixed64,6,opt,name=morn,proto3" json:"morn,omitempty"`
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{14}
}

func (x *Temperature) GetDay() float64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Temperature) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Temperature) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Temperature) GetNight() float64 {
	if x != nil {
		return x.Night
	}
	return 0
}

func (x *Temperature) GetEve() float64 {
	if x != nil {
		return x.Eve
	}
	return 0
}

func (x *Temperature) GetMorn() float64 {
	if x != nil {
		return x.Morn
	}
	return 0
}

type FeelsLike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day   float64 `protobuf:"fixed64,1,opt,name=day,proto3" json:"day,omitempty"`
	Night float64 `protobuf:"fixed64,2,opt,name=night,proto3" json:"night,omitempty"`
	Eve   float64 `protobuf:"fixed64,3,opt,name=eve,proto3" json:"eve,omitempty"`
	Morn  float64 `protobuf:"fixed64,4,opt,name=morn,proto3" json:"morn,omitempty"`
}

func (x *FeelsLike) Reset() {
	*x = FeelsLike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeelsLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeelsLike) ProtoMessage() {}

func (x *FeelsLike) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeelsLike.ProtoReflect.Descriptor instead.
func (*FeelsLike) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{15}
}

func (x *FeelsLike) GetDay() float64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *FeelsLike) GetNight() float64 {
	if x != nil {
		return x.Night
	}
	return 0
}

func (x *FeelsLike) GetEve() float64 {
	if x != nil {
		return x.Eve
	}
	return 0
}

func (x *FeelsLike) GetMorn() float64 {
	if x != nil {
		return x.Morn
	}
	return 0
}

type WeatherCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Main        string `protobuf:"bytes,2,opt,name=main,proto3" json:"main,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon        string `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *WeatherCondition) Reset() {
	*x = WeatherCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherCondition) ProtoMessage() {}

func (x *WeatherCondition) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherCondition.ProtoReflect.Descriptor instead.
func (*WeatherCondition) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{16}
}

func (x *WeatherCondition) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WeatherCondition) GetMain() string {
	if x != nil {
		return x.Main
	}
	return ""
}

func (x *WeatherCondition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WeatherCondition) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderName  string   `protobuf:"bytes,1,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Event       string   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Start       int64    `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End         int64    `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	Description string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Alert) Reset() {
	*x = Alert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{17}
}

func (x *Alert) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Alert) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Alert) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Alert) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_weather_proto protoreflect.FileDescriptor

var file_weather_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x78, 0x0a, 0x0e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x61, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x22, 0x4f, 0x0a, 0x12, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0f, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e,
	0x67, 0x22, 0xb1, 0x03, 0x0a, 0x13, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x31, 0x0a,
	0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x57,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x04,
	0x77, 0x69, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x64, 0x12, 0x1f, 0x0a,
	0x04, 0x72, 0x61, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x52, 0x61, 0x69, 0x6e, 0x52, 0x04, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x25,
	0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x52, 0x06, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x64, 0x74, 0x12, 0x1c, 0x0a, 0x03, 0x73, 0x79, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x52, 0x03,
	0x73, 0x79, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x63, 0x6f, 0x64, 0x22, 0x2b, 0x0a, 0x05, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c,
	0x61, 0x74, 0x22, 0xea, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x65, 0x65, 0x6c, 0x73, 0x5f,
	0x6c, 0x69, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x66, 0x65, 0x65, 0x6c,
	0x73, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x6d, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x74, 0x65, 0x6d, 0x70, 0x4d, 0x69, 0x6e,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x74, 0x65, 0x6d, 0x70, 0x4d, 0x61, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x61, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x61, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6e, 0x64, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x67, 0x72, 0x6e, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22,
	0x42, 0x0a, 0x04, 0x57, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x65, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x65, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x67, 0x75, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x67,
	0x75, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x04, 0x52, 0x61, 0x69, 0x6e, 0x12, 0x11, 0x0a, 0x05, 0x6f,
	0x6e, 0x65, 0x5f, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x31, 0x68, 0x12, 0x13,
	0x0a, 0x07, 0x74, 0x68, 0x72, 0x65, 0x65, 0x5f, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x02, 0x33, 0x68, 0x22, 0x1a, 0x0a, 0x06, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x22,
	0x75, 0x0a, 0x03, 0x53, 0x79, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6e, 0x72, 0x69, 0x73, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x75, 0x6e, 0x72, 0x69, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x22, 0xc2, 0x02, 0x0a, 0x0f, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69,
	0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a,
	0x08, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x6c, 0x79, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x6c, 0x79,
	0x52, 0x08, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x06, 0x68, 0x6f,
	0x75, 0x72, 0x6c, 0x79, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x48, 0x6f, 0x75, 0x72, 0x6c, 0x79, 0x52, 0x06, 0x68, 0x6f, 0x75, 0x72, 0x6c,
	0x79, 0x12, 0x22, 0x0a, 0x05, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x05,
	0x64, 0x61, 0x69, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x52, 0x06, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x22, 0xa7, 0x03, 0x0a, 0x07,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x64, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6e, 0x72, 0x69,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x75, 0x6e, 0x72, 0x69, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x65, 0x65, 0x6c, 0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x66, 0x65, 0x65, 0x6c, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x77, 0x5f, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x65, 0x77, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x76, 0x69, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x75, 0x76, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x76,
	0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x77,
	0x69, 0x6e, 0x64, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x77, 0x69, 0x6e, 0x64, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x69,
	0x6e, 0x64, 0x5f, 0x64, 0x65, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x69,
	0x6e, 0x64, 0x44, 0x65, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x5f, 0x67, 0x75,
	0x73, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x64, 0x47, 0x75,
	0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x0f, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x57, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x77, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x08, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x6c,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x64,
	0x74, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x86, 0x03, 0x0a, 0x06, 0x48, 0x6f, 0x75, 0x72,
	0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x64, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x65, 0x65, 0x6c, 0x73, 0x5f,
	0x6c, 0x69, 0x6b, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x66, 0x65, 0x65, 0x6c,
	0x73, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x65, 0x77, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x64, 0x65, 0x77, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x76,
	0x69, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x75, 0x76, 0x69, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x69, 0x6e, 0x64, 0x5f, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x53, 0x70,
	0x65, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x64, 0x5f, 0x64, 0x65, 0x67, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x67, 0x12, 0x1b,
	0x0a, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x5f, 0x67, 0x75, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x64, 0x47, 0x75, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x77,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x6f, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x70, 0x6f, 0x70,
	0x22, 0xc0, 0x04, 0x0a, 0x05, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x64, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x6e, 0x72, 0x69, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x75, 0x6e,
	0x72, 0x69, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x6f, 0x6f, 0x6e, 0x72, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x6d, 0x6f, 0x6f, 0x6e, 0x72, 0x69, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x6f, 0x6e,
	0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x6f, 0x6e, 0x73,
	0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x6f, 0x6e, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6d, 0x6f, 0x6f, 0x6e, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x26, 0x0a, 0x04, 0x74,
	0x65, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x04, 0x74,
	0x65, 0x6d, 0x70, 0x12, 0x2f, 0x0a, 0x0a, 0x66, 0x65, 0x65, 0x6c, 0x73, 0x5f, 0x6c, 0x69, 0x6b,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x46, 0x65, 0x65, 0x6c, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x09, 0x66, 0x65, 0x65, 0x6c, 0x73,
	0x4c, 0x69, 0x6b, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x77, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x64, 0x65, 0x77, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x69, 0x6e,
	0x64, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x77,
	0x69, 0x6e, 0x64, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x64,
	0x5f, 0x64, 0x65, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x64,
	0x44, 0x65, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x5f, 0x67, 0x75, 0x73, 0x74,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x64, 0x47, 0x75, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x10, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x77, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x6f, 0x70, 0x18, 0x12, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x70, 0x6f, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x69, 0x6e, 0x18, 0x13, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x76, 0x69, 0x18, 0x14, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x75, 0x76, 0x69, 0x22, 0x7f, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x64, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x65, 0x76, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x72, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x6d, 0x6f, 0x72, 0x6e, 0x22, 0x59, 0x0a, 0x09, 0x46, 0x65, 0x65, 0x6c, 0x73, 0x4c, 0x69, 0x6b,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x76, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x65, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x6f, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6d, 0x6f, 0x72, 0x6e, 0x22,
	0x6c, 0x0a, 0x10, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x22, 0x9c, 0x01,
	0x0a, 0x05, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x42, 0x27, 0x5a, 0x25,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x54, 0x55, 0x2d, 0x53,
	0x65, 0x6d, 0x61, 0x74, 0x58, 0x2f, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_weather_proto_rawDescOnce sync.Once
	file_weather_proto_rawDescData = file_weather_proto_rawDesc
)

func file_weather_proto_rawDescGZIP() []byte {
	file_weather_proto_rawDescOnce.Do(func() {
		file_weather_proto_rawDescData = protoimpl.X.CompressGZIP(file_weather_proto_rawDescData)
	})
	return file_weather_proto_rawDescData
}

var file_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_weather_proto_goTypes = []any{
	(*WeatherRequest)(nil),      // 0: types.WeatherRequest
	(*WeatherCityRequest)(nil),  // 1: types.WeatherCityRequest
	(*WeatherCityResponse)(nil), // 2: types.WeatherCityResponse
	(*Coord)(nil),               // 3: types.Coord
	(*MainWeather)(nil),         // 4: types.MainWeather
	(*Wind)(nil),                // 5: types.Wind
	(*Rain)(nil),                // 6: types.Rain
	(*Clouds)(nil),              // 7: types.Clouds
	(*Sys)(nil),                 // 8: types.Sys
	(*WeatherResponse)(nil),     // 9: types.WeatherResponse
	(*Current)(nil),             // 10: types.Current
	(*Minutely)(nil),            // 11: types.Minutely
	(*Hourly)(nil),              // 12: types.Hourly
	(*Daily)(nil),               // 13: types.Daily
	(*Temperature)(nil),         // 14: types.Temperature
	(*FeelsLike)(nil),           // 15: types.FeelsLike
	(*WeatherCondition)(nil),    // 16: types.WeatherCondition
	(*Alert)(nil),               // 17: types.Alert
}
var file_weather_proto_depIdxs = []int32{
	3,  // 0: types.WeatherCityResponse.coord:type_name -> types.Coord
	16, // 1: types.WeatherCityResponse.weather:type_name -> types.WeatherCondition
	4,  // 2: types.WeatherCityResponse.main:type_name -> types.MainWeather
	5,  // 3: types.WeatherCityResponse.wind:type_name -> types.Wind
	6,  // 4: types.WeatherCityResponse.rain:type_name -> types.Rain
	7,  // 5: types.WeatherCityResponse.clouds:type_name -> types.Clouds
	8,  // 6: types.WeatherCityResponse.sys:type_name -> types.Sys
	10, // 7: types.WeatherResponse.current:type_name -> types.Current
	11, // 8: types.WeatherResponse.minutely:type_name -> types.Minutely
	12, // 9: types.WeatherResponse.hourly:type_name -> types.Hourly
	13, // 10: types.WeatherResponse.daily:type_name -> types.Daily
	17, // 11: types.WeatherResponse.alerts:type_name -> types.Alert
	16, // 12: types.Current.weather:type_name -> types.WeatherCondition
	16, // 13: types.Hourly.weather:type_name -> types.WeatherCondition
	14, // 14: types.Daily.temp:type_name -> types.Temperature
	15, // 15: types.Daily.feels_like:type_name -> types.FeelsLike
	16, // 16: types.Daily.weather:type_name -> types.WeatherCondition
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_weather_proto_init() }
func file_weather_proto_init() {
	if File_weather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_weather_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WeatherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WeatherCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WeatherCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Coord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MainWeather); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Wind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Rain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Clouds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Sys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*WeatherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Current); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Minutely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Hourly); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Daily); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Temperature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*FeelsLike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*WeatherCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weather_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*Alert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_weather_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weather_proto_goTypes,
		DependencyIndexes: file_weather_proto_depIdxs,
		MessageInfos:      file_weather_proto_msgTypes,
	}.Build()
	File_weather_proto = out.File
	file_weather_proto_rawDesc = nil
	file_weather_proto_goTypes = nil
	file_weather_proto_depIdxs = nil
}
